syntax = "proto3";

// # Payment Transaction API Service Suite
//
// **Project Details:**
// - **Project ID:** buf-gradle-demo
// - **Authentication:** JWT
// - **Documentation:** https://karthik78180.github.io/buf-gradle-demo/

package schema.service.v1;

import "payments/v1/transaction.proto";

option java_multiple_files = true;
option java_package = "com.example.service.v1";

// TransactionService provides operations for payment transactions.
service TransactionService {
  // GetTransaction retrieves a transaction by storeName and returns updated Transaction with dummy values.
  rpc GetTransaction(payments.v1.GetTransactionRequest) returns (payments.v1.GetTransactionResponse) {}
}
